// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    HomeDeveloperDetails: typeof import('./src/components/home/HomeDeveloperDetails/HomeDeveloperDetails.vue')['default']
    HomeDeveloperPresentation: typeof import('./src/components/home/HomeDeveloperPresentation/HomeDeveloperPresentation.vue')['default']
    HomeWelcomeScreen: typeof import('./src/components/home/HomeWelcomeScreen/HomeWelcomeScreen.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    ScrollBottomButton: typeof import('./src/components/home/HomeWelcomeScreen/components/ScrollBottomButton.vue')['default']
    SocialsBar: typeof import('./src/components/SocialsBar/SocialsBar.vue')['default']
    TechnologiesCarousel: typeof import('./src/components/TechnologiesCarousel/TechnologiesCarousel.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar/TheNavbar.vue')['default']
    UiBrandDivider: typeof import('./src/components/ui/UiBrandDivider/UiBrandDivider.vue')['default']
    UiBurger: typeof import('./src/components/ui/UiBurger/UiBurger.vue')['default']
    UiButton: typeof import('./src/components/ui/UiButton/UiButton.vue')['default']
  }
}

export { }
